config/routes.rb
Spacerps::Application.routes.draw do
  get "pages/welcome"
  get "pages/help"
  get "pages/play"
  get "pages/hiscores"

  resources :users
  resources :pages
  resources :sessions, only: [:new, :create, :destroy]
 
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  root 'pages#welcome'

  

end

app/models/enemy.rb
class Enemy < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { self.email = email.downcase }
	before_create :create_remember_token
  validates :name,  presence: true, length: { minimum: 3, maximum: 15 },
  	uniqueness: { case_sensitive: false }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
  	uniqueness: { case_sensitive: false }
	has_secure_password
  	validates :password, length: { minimum: 6 }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

 def index
    @enemies = Enemy.all
  end

  def welcome
  end

  def help
  end

  def play
  end

  def hiscores
  end

 def show
    @user = User.find(params[:id])
  end

 def set_enemy
      @enemy = Enemy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def enemy_params
      params.require(:enemy).permit(:id, :hullpoints, :shieldpoints, :race, :enshipname)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def new
  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end



  def destroy
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :shipname, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
	def current_enemy=(enemy)
    @current_enemy= enemy
  end

  def opponent
  	opponent = 1
  end

  def current_enemy
    @current_enemy = Enemy.find(opponent)
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
	 def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Spacerps</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%#= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/help.html.erb
<h1>Pages#help</h1>
<p>Find me in app/views/pages/help.html.erb</p>

app/views/pages/hiscores.html.erb
<h1>Pages#hiscores</h1>
<p>Find me in app/views/pages/hiscores.html.erb</p>

app/views/pages/play.html.erb
<%= javascript_include_tag "mainplay" %>
<script type="text/javascript">
  var enshieldpoints = "<%= current_enemy.shieldpoints %>";
  var enhullpoints = "<%= current_enemy.hullpoints %>";
  BeginFight();
</script>

<!-- preloading images so they don't flicker -->
<script type="text/javascript">
if (document.images) {
    img1 = new Image();
    img1.src = "PlayerShipFullDamage.png";
    img2 = new Image();
    img2.src = "PlayerShipMinorDamage.png";
    img3 = new Image();
    img3.src = "EnemyShipFullDamage.png";
    img4 = new Image();
    img4.src = "EnemyShipMinorDamage.png";
}
</script>
<body onload="BeginFight()">

<h1>Pages#play</h1>


<p>
  <strong>Enemy Race:</strong>
  <%= current_enemy.race %>
</p>

<p>
  <strong>Enemy Ship Name:</strong>
  <%= current_enemy.enshipname %>
</p>

<p>
  <strong>Enemy Hullpoints:</strong>
  <%= current_enemy.hullpoints %>
</p>

<button id="PlayRock" onclick="PlayRock()">Fire Rock Missile</button>
<button id="PlayPaper" onclick="PlayPaper()">Fire Plasmatic Paper</button>
<button id="PlayScissors" onclick="PlayScissors()">Fire Scissor Slicer</button>

<p>
  <strong>Results:</strong>
  <div id="PlayerMoveShow"></div>
  <div id="EnemyMoveShow"></div>
  <div id="AttackResultShow"></div>
</p>

<center>
<table border="0">
<tr>
<td><center>Captain <%= current_user.name %> - GSS <%= current_user.shipname %></center></td>
<td><center><%= current_enemy.enshipname %></center></td>
</tr>
<tr>
<td style="width:320px; height:240px; background-image:url(/assets/PlayerShip.png)"><div id="playershipimg"></div></td>
<td style="width:320px; height:240px; background-image:url(/assets/EnemyShip.png)"><div id="enemyshipimg"></div></td>
</tr>
</table>

<table border="1">
<tr>
<td>Player Hull Points</td>
<td>Player Shield Points</td>
<td>Enemy Hull Points</td>
<td>Enemy Shield Points</td>
</tr>
<tr>
<td><div id="playerhpshow"></div></td>
<td><div id="playerspshow"></div></td>
<td><div id="enemyhpshow"></div></td>
<td><div id="enemyspshow"></div></td>
</tr>
</table>
<div id="fightresultshow"></div>
<div id="fighttallyresultshow"></div>
</center>

app/views/pages/welcome.html.erb
<h1>Pages#welcome</h1>
<p>Welcome to Space Rock, Paper, Scissors!</p>

Login or sign up to play now!

<% provide(:title, "Sign in") %>
<h1>Sign in</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(:session, url: sessions_path) do |f| %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.submit "Sign in", class: "btn btn-large btn-primary" %>
    <% end %>

    <p>New user? <%= link_to "Sign up now!", signup_path %></p>
  </div>
</div>

app/views/users/_form.html.erb
  

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<center>
      <%= f.label :name, "Captain's Name" %><br>
      Captain <%= f.text_field :name %><br><br>

      <%= f.label :shipname, "Ship Name" %><br>
      GSS <%= f.text_field :shipname %><br><br>

      <%= f.label :email %><br>
      <%= f.text_field :email %><br><br>

      <%= f.label :password %><br>
      <%= f.password_field :password %><br><br>

      <%= f.label :password_confirmation, "Password Confirmation" %><br>
      <%= f.password_field :password_confirmation %><br><br>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing Captains</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
     <%# <th>Password digest</th> %>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
      <%#  <td><%= user.password_digest %>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<center>
	<h1>New Captain</h1>

<%= render 'form' %>

<br><%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

Welcome, Captain <%= @user.name %>!
You command the GSS <%= @user.shipname %>.

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Total Rock Missiles:</strong>
  <%= @user.rocks %>
</p>

<p>
  <strong>Total Plasmatic Papers:</strong>
  <%= @user.papers %>
</p>

<p>
  <strong>Total Scissor Slicers:</strong>
  <%= @user.scissors %>
</p>






<%= link_to 'Play', pages_play_path %> |
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/test.html.erb
<h1>Pages#play</h1>
<p>KILL THE BADDIES</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>